os:
  - linux
  - osx
  - windows

language: rust
rust:
  - 1.38.0
cache: cargo

install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install make          ; fi

before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  
script:
  - make

deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    branch: master

