# blocklist
branches:
  except:
  - egg-herbie-deploy-osx
  - egg-herbie-deploy-windows
  - egg-herbie-deploy-linux

os:
  - linux
  - osx
  - windows

language: rust
rust:
  - 1.38.0
cache: cargo

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION="7.3" JOB="${STABILITY}"

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install make          ; fi

before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  
script:
  - make
  - cargo build --release
  - raco test ./

deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    branch: master

