# blocklist
branches:
  except:
  - egg-herbie-deploy-osx
  - egg-herbie-deploy-windows
  - egg-herbie-deploy-linux

os:
  - linux
  - osx
  - windows

language: rust
rust:
  - 1.38.0
cache: cargo

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION="7.3" JOB="${STABILITY}"

# install racket for testing on linux
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cat ../travis-racket/install-racket.sh | bash          ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH="${RACKET_DIR}/bin:${PATH}"          ; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install make          ; fi

before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  
script:
  - make
  - cargo build --release
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then raco test ./          ; fi

deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    branch: master

