os:
  - linux
  - osx
  - windows

language: rust
rust:
  - 1.38.0
cache: cargo
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  
script: make  

deploy:
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: egg-herbie-deploy-$(TRAVIS_OS_NAME)