os:
  - linux
  - osx
  - windows

language: rust
rust:
  - 1.38.0
cache: cargo

install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install make          ; fi

before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  
script:
  - make
  - rm .gitignore # remove gitignore so deployment gets target folder
  - rm .travis.yml # remove travis for deployed branches

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: egg-herbie-deploy-$TRAVIS_OS_NAME
  on:
    branch: master
