name: Build on all three OSes

on:
  push:
    branches:
      - master
      - gh-actions

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v0.5
      - name: Install Rust compiler
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            default: true
            override: true
            components: rustfmt, clippy
      - run: cargo clippy --tests
        continue-on-error: true
      - run: cargo test
      - run: cargo fmt -- --check
      - run: cargo build --release
      - run: raco test ./
      - run: bash ./deploy.sh ${{ matrix.os }}
